-- SQL Migration 2021-02-08T17.36.22.814830 userstable
-- Userstable

CREATE TABLE IF NOT EXISTS PHONE(
    `ID` VARCHAR(36) DEFAULT(UUID()) PRIMARY KEY,
    `COUNTRY_CODE` VARCHAR(7) NOT NULL,
    `NUMBER` VARCHAR(12) NOT NULL,

    CONSTRAINT `UC_Country_Code_Number` UNIQUE (`COUNTRY_CODE`, `NUMBER`)
);
